### ISSUE TITLE
feat: Add handling for Swift 8.x versions (future)

### ISSUE THREAD

**Issue by dayaffe** [awslabs/aws-sdk-swift#1205]
### Describe the feature

Unfortunately there isn't a way to grab the compiled swift programmatically and so we must resort to the compiler directives to produce a version string. We are checking for quite a few versions in the future, that may never exist, in order to future proof our current SDKs. Ideally, all current SDKs should compile on future Swift versions unless that Swift version introduces a breaking change.

This issue addresses the following comment:
[TODO add handling for Swift 8.x versions when Swift 6.0 is released.](https://github.com/smithy-lang/smithy-swift/blob/53fbde27f536f4287edfd4ff08bb5ebe8dc75169/Sources/ClientRuntime/Util/SwiftVersion.swift#L15)

### Use Case

Support future Swift 8.x versions in smithy-swift now so that we can remove this TODO statement from our backlog.

### Proposed Solution

Following the same coding pattern used for Swift 7.x [here](https://github.com/smithy-lang/smithy-swift/blob/53fbde27f536f4287edfd4ff08bb5ebe8dc75169/Sources/ClientRuntime/Util/SwiftVersion.swift#L85C15-L85C15)

### Other Information

Related Issue: #710 

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by sichanyoo** [comment]
This TODO will be deleted as part of clean-up.

**Comment by jbelkins** [comment]
Swift 6 will be released soon.  The gap between Swift 5 & 6 was five years, and I don't expect that Apple / Swift core team will be in any hurry to release Swift 7 let alone 8 anytime soon.

Further, it's not reasonable to expect that current versions of the SDK will support future Swift versions because major versions of the language typically bring breaking changes.

For that reason, this TODO should be deleted, and any code to support Swift 7 may be removed if desired as well.
