### ISSUE TITLE
Implement "S3 Expires Shape Customization" SEP

### ISSUE THREAD

**Issue by smivij** [awslabs/aws-sdk-swift#1400]

**Comment by sichanyoo** [comment]
IF Smithy team makes the changes before we go GA, no action should be needed from Swift SDK team.
Needs further investigation on:
- Whether protocol tests have been written / wip by Smithy team for this
- When the Smithy team is planning to change the type of `Expires` shape from `timestamp` to `string` (as of 3/11/24, it is still `timestamp`)

**Comment by sichanyoo** [comment]
AWS Swift SDK has a `SwiftIntegration` in place that "re-shapes" Expires member shape in S3 model to target `smithy.api#String` instead of `smithy.api#Timestamp` IF it is nested under `XYZOutput` shapes.

[This](https://github.com/awslabs/aws-sdk-swift/blob/main/codegen/smithy-aws-swift-codegen/src/main/kotlin/software/amazon/smithy/aws/swift/codegen/customization/s3/S3Expires.kt) is the integration, and it was added with [this PR](https://github.com/awslabs/aws-sdk-swift/pull/709).

This means that even if Smithy team changes Expires shape to be String in C2J / Smithy model resulting from C2J tool, the behavior of Swift SDK **will remain the same for deserialization** because we already treat it as string and copy the string from HTTP header into string property of the output type.

However, the planned changes by Smithy team outlined by `--/seps/accepted/shared/s3-expires-shape-customization.md` SEP includes `Expires` shape nested under input shapes as well (SIMs: `SMITHY-2535` & `SMITHY-2536`). I'll be putting up a PR soon that links this issue, that expands pre-existing integration to include `Expires` nested under input shapes as well.

**Comment by dayaffe** [comment]
Released in 0.43
