### ISSUE TITLE
AWSKinesisVideo 有flutter版本吗？

### ISSUE THREAD

**Issue by zhangshouyin** [awslabs/aws-sdk-swift#1497]
### Describe the feature

我的工程是flutter工程，想使用AWSKinesisVideo SDK，但是AWSKinesisVideo 只有Swift版本。
我问一下AWSKinesisVideo 有flutter版本吗？如果有可以给我一个链接吗？
Does AWSKinesisVideo have a Flutter version? My project is a Flutter project and I want to use the AWSKinesisVideo SDK, but it's only available in Swift. Can you provide a link to a Flutter version of AWSKinesisVideo if it exists?

### Use Case

used in flutter 

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by sichanyoo** [comment]
Hello, thanks for reaching out with the question.

The client for AWSKinesisVideo service is available in all other official AWS SDKs (e.g., Java V2, Kotlin, etc.). Note you won't see the code for the client in Java V2 and Kotlin repo because Java V2 and Kotlin don't check in the SDK code into their repo. Customers of those SDKs pull the SDK down from Maven within their Gradle project.

There is no official AWS SDK for Dart, and hence no official client code for AWS Kinesis Video for Dart. If there is a way in Flutter to direct code path based on the platform the app is in, maybe you could use that to run Swift SDK for Apple platforms, Kotlin SDK for android, etc.

Good news is that AWS Amplify has support for Flutter, and you might be able to work with AWS Kinesis Service via REST API as shown in their doc [here](https://docs.amplify.aws/gen1/flutter/build-a-backend/restapi/set-up-rest-api/). Their repo is [here](https://github.com/aws-amplify/amplify-flutter?tab=readme-ov-file).

Hopefully that clears some things up!

**Comment by zhangshouyin** [comment]
> 您好，感谢您提出问题。
> 
> AWSKinesisVideo 服务的客户端在所有其他官方 AWS 开发工具包（例如 Java V2、Kotlin 等）中均可用。请注意，您不会在 Java V2 和 Kotlin 存储库中看到客户端的代码，因为 Java V2 和 Kotlin 不会将 SDK 代码签入其存储库中。这些 SDK 的客户在其 Gradle 项目中从 Maven 中提取 SDK。
> 
> 没有适用于 Dart 的官方 AWS 开发工具包，因此没有适用于 Dart 的 AWS Kinesis Video 的官方客户端代码。如果 Flutter 中有一种方法可以根据应用程序所在的平台来引导代码路径，也许您可​​以使用它来运行适用于 Apple 平台的 Swift SDK、适用于 Android 的 Kotlin SDK 等。
> 
> 好消息是 AWS Amplify 支持 Flutter，您或许可以通过 REST API 使用 AWS Kinesis Service，如其文档[所示](https://docs.amplify.aws/gen1/flutter/build-a-backend/restapi/set-up-rest-api/)。他们的仓库在[这里](https://github.com/aws-amplify/amplify-flutter?tab=readme-ov-file)。
> 
> 希望这能澄清一些事情！

okay， Thank you very much @sichanyoo
