### ISSUE TITLE
Requesting support for CocoaPods

### ISSUE THREAD

**Issue by imraymondlee** [awslabs/aws-sdk-swift#1624]
### Describe the feature

This package is only available through Swift Package Manager I would like to request a feature for CocoaPods. Other users would also be interested in this as CocoaPods has over 100 thousand libraries and is used in over 3 million apps. As https://github.com/aws-amplify/aws-sdk-ios is no longer the recommended AWS SDK for iOS, there will be no AWS SDK for CocoaPods users.

### Use Case

We have been using aws-sdk-ios and we are migrating to aws-sdk-swift as dependencies of our own package. One requirement of our package is that we need to distribute it to CocoaPods. As [CocoaPods can't have Swift Package Manager dependencies](https://github.com/CocoaPods/CocoaPods/issues/11942), we are unable to distribute our package through CocoaPods.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by jbelkins** [comment]
https://blog.cocoapods.org/CocoaPods-Support-Plans/

Today CocoaPods was placed into "maintenance mode" by its maintainers.  While it will continue to receive security and other essential fixes, it is clear that CocoaPods does not have a future outside its current use cases.

Because the work to add CocoaPods distribution to AWS SDK for Swift and the ongoing operational workload to distribute via CocoaPods would be significant, we do not plan to distribute this SDK via CocoaPods.

Closing this issue.
