### ISSUE TITLE
Improve integration with SwiftLog

### ISSUE THREAD

**Issue by 0xTim** [awslabs/aws-sdk-swift#462]
The server-side Swift community uses SwiftLog throughout the ecosystem. It would be great to make the integration of `SwiftLog` easier with the SDK.

The main step would be providing an extension to make `SwiftLog`'s `Logger` conform to `LogAgent` to allow it to be passed to the client configuration easily. Since anyone with their own logger (everyone on the server) would need to write this, it makes sense to provide it as part of the SDK as it's already a dependency.

**Comment by kneekey23** [comment]
@wooj2 I believe we already have this inside ClientRuntime we just need to expose it and make it public to address this.

**Comment by kneekey23** [comment]
@0xTim hi Tim, we already have this here: https://github.com/awslabs/smithy-swift/blob/main/Packages/ClientRuntime/Sources/Logging/SwiftLog%2BLogAgent.swift if we just expose this and make it public, woudl that satisfy your request?

**Comment by 0xTim** [comment]
I think that should work yes.

Yes that's correct. Let's say you're trying to integrate a standard server-side Swift app, you'll need to bootstrap your own logger so it's available across the entire application etc

**Comment by wooj2** [comment]
Hi @0xTim,

Sorry, but I'm trying to better understand your requirements.  Based on your original post it sounds like you want to be able to pass in an instance of SwiftLog's Logger into a client configuration.  Based on my understanding, you can already do this with the latest version of the SDK (0.0.16).

For example, I was able to get the following to compile:
```
import ClientRuntime
import AWSPolly
import Logging

struct MySDKRuntimeConfiguration: SDKRuntimeConfiguration {
    public let retryer: SDKRetryer
    public var clientLogMode: ClientLogMode
    public var logger: LogAgent

    public init(_ clientName: String, clientLogMode: ClientLogMode, logger: SwiftLogger) throws {
        self.retryer = try SDKRetryer()
        self.logger = logger
        self.clientLogMode = clientLogMode
    }
}

func pollyLoggingClient() throws{
    let myLogAgent = SwiftLogger(label: "MyOwnLogger")
    let runtimeConfiguration = try MySDKRuntimeConfiguration("PollyClient", clientLogMode: .request, logger: myLogAgent)
    let pollyConfig = try PollyClient.PollyClientConfiguration(credentialsProvider: nil,
                                                               endpointResolver: nil,
                                                               frameworkMetadata: nil,
                                                               region: "us-west-2",
                                                               regionResolver: nil,
                                                               signingRegion: nil,
                                                               runtimeConfig: runtimeConfiguration)
    let pollyClient = PollyClient(config: pollyConfig)
}
try pollyLoggingClient()
```

As a result of this code above, are you expecting that the SDK will use the instance of `myLogAgent` to log all info/debug/warn/etc.. messages that are being executed within in the SDK (or are you expecting something else)?

**Comment by 0xTim** [comment]
Ah if that works that's great. Yeah I'm expecting the SDK to log out to the provided instance of SwiftLog, log messages to be ignored if they're at the `debug` level and the `Logger.logLevel` is set to `.info` etc

If that already works then this can be closed. (Might be good to add it to the README for server-side devs)

**Comment by wooj2** [comment]
@0xTim -

Heh, well, the code sample above should compile, but upon further inspection, I noticed that there are some cases in AWSClientRuntime where we are not using the logger parameter passed in through the configuration, and instead using a newly created instance of SwiftLogger.  For example, [ProfileRegionProvider](https://github.com/awslabs/aws-sdk-swift/blob/e3e4097b1a3427b40c67684f16d459ce562711f3/AWSClientRuntime/Sources/Regions/ProfileRegionResolver.swift#L19)

So, based on the current state of the code, passing in your instance of SwiftLogger probably won't achieve what you are looking for.  In order to accomplish what you're asking, it sounds like we would need to find a way to plumb that instance (somehow) to each place that wants to log.  If my understanding is correct, it seems like this could be a pretty invasive code change, which makes me hesitant with moving forward on unless there is a strong use case around this.  Maybe you can describe why this is necessary?

**Comment by fabianfett** [comment]
Oh, I've just been made aware, that you already integrate with Swift-Log (my bad, I didn't see swift-log being imported in the Package.swift):
https://github.com/awslabs/smithy-swift/blob/main/Packages/ClientRuntime/Sources/Logging/SDKLoggingSystem.swift

It looks to me, that you created your own bootstrap method around the default swift-log method to allow users to customize the log level per service. The same functionality can also be achieved on a per request basis by passing logger around.

Users can set the logLevel on a logger and the logger will only emit logs that are of a same or higher log level. This way users who see issues with a specific request can enable full fidelity logging only for this one request instead of for a complete service.

You can see an example use-case in lambda:

https://github.com/swift-server/swift-aws-lambda-runtime/blob/afab5102a1a82649c7caa15ffa294cc782051f49/Sources/AWSLambdaRuntimeCore/LambdaRuntime.swift

Here we create a single logger, that we pass to the user on every request on context. At every request the `lifecycleId` on the logger will be increased. Adding valuable information, after how many request some functionality might break.

**Comment by ktoso** [comment]
Wait, wait, wait @fabianfett... we should not double-down-on and suddenly go into the "pass around the logger" style, especially in libraries which are not married to it yet. In the wake of Swift Concurrency and it's [task local values](https://github.com/apple/swift-evolution/blob/main/proposals/0311-task-locals.md), as well as our plans to stabilize the tracing APIs early in 2022, we need to consider the long term shape of how we want to solve tracing properly. 

The current style ("always pass around a logger, from top to bottom, through _all_ calls") is, IMHO, a workaround for missing features which we just got (task locals) and are working on finalizing (swift-distributed-tracing and connecting baggage with swift-log).

**Comment by kneekey23** [comment]
@ktoso @fabianfett @0xTim to be clear, @wooj2 and I still aren't clear on what the ask is here then if you don't want us to pass the logger instance around (there's only 1-2 places where a new one is being created that would need to be cleaned up for reference). If someone could please elaborate on what the issue is here so that we can make the requested code changes and hopefully resolve this issue soon, that would be great! We would really like to make sure you can do what it is you desire!

**Comment by fabianfett** [comment]
Okay, I may have caused more confusion, than actually explaining the issue correctly yesterday. Sorry, this was not my intention.

I guess we should divide the discussion into two topics. How does logging work with swift-log today, to better understand the initial request and how shall logging look in the future and what should be done today (spoiler: wait and drink tea).

## How does swift-log work today

As noted yesterday, currently a lot of swift-server frameworks use a Logger, that is passed around, to add metadata to all the log lines that the logger emits. For this reason you will see the logger often as the last argument in calls to services. Let's take the AsyncHTTPClient for example:

```swift
struct HTTPClient {
  public func get(url: String, deadline: NIODeadline? = nil, logger: Logger) -> EventLoopFuture<Response>
}
```

Here we can see, that the user shall pass a logger on every call. If the user has created a logger before:

```swift
var logger = Logger(label: "my-request-logger")
logger[metadataKey: "request-id"] = "123"
```

all logs that are emitted inside the `HTTPClient` will have an additional request-id field with the value "123", which is important for correlating log requests.

Let's look at the code from the last AWS SDK release: Instead of passing a logger to the SDK on every call, one configures a `S3Client` with an `S3Client.S3ClientConfiguration`. On the `S3Client.S3ClientConfiguration` you expose a `logger: LogAgent` property which a user can set. The LogAgent is a protocol around the `swift-log` `Logger`. This means in turn, that to get the correct metadata from every request a user would need to create and destroy a new `S3Client` on every request to the server.

While this is certainly an approach that can be taken, there might be a number of drawbacks to it. Especially users need to be made aware that they need to use the same `ClientRuntime.HttpClientConfiguration` to ensure the same `HttpClientEngine` is used everywhere to support connection-pooling between requests.

I hope this makes yesterday's discussion clearer. If you have follow up questions please reach out.

## What the future will look like for swift-log

@ktoso and @slashmo are currently looking into ways to propagate context without explicit `Logger` passing to downstream functions. This shall happen by using [TaskLocals](https://github.com/apple/swift-evolution/blob/main/proposals/0311-task-locals.md). Since this work is intertwined with the `swift-distributed-tracing` work, it is mainly happening in the distributed-tracing repositories.

We recommend to not change any APIs at the moment (especially since you want to go all in on async/await) and add logging functionality once context propagation has been added through TaskLocals.

If you want to follow this work, have a look at this [PR](https://github.com/apple/swift-log/pull/206).

**Comment by kneekey23** [comment]
@fabianfett this sounds to me like for the time being, we should do nothing. The PRs to refactor the entire SDK to use the new concurrency primitives are actually already open and as soon as I can get CI to pass (need the toolchain to include xctest async support for linux), they will be merged and the entire sdk will be async/await. Seems like we can just put this issue on hold for now?

**Comment by 0xTim** [comment]
As the issue creator - the original issue is fine and a logger can be used in most places. It was also a misunderstanding on my part apart bootstrapping other loggers so that's been resolved now. Happy to close this and create a new ones for controlling log levels etc and whatever the future direction should be once tracing and logging are sorted

**Comment by kneekey23** [comment]
I would appreciate this issue now being closed since it's a separate issue now that looks like will be worked on in the future as the logging story evolves over time with the new concurrency primitives. @0xTim But when you do create another issue, feel free to reference this one for context ;)

**Comment by 0xTim** [comment]
Fine by me!
