### ISSUE TITLE
Compile error when adding dependency for AWSIoT on Linux

### ISSUE THREAD

**Issue by dave-moser** [awslabs/aws-sdk-swift#495]
## Description
Attempting to compile an SPM project using version 0.0.15 of the AWSSwiftSDK and adding the AWSIoT module.  During the compile, an error is thrown stopping the compile.  I am performing the compile on Linux in the swift:5.4.3-amazonlinux2 docker image. I built a similar project in Xcode and did NOT get an error.  I was able to build.

## Context
I am ultimately attempting to write a Lambda function in Swift that interacts with AWS IoT Core.

## Environment
* AWS Swift SDK version used: 0.0.15
* Operating System and version (iOS/macOS/Linux): Linux
* Xcode version (if applicable):
* Swift compiler version (if applicable): 5.4.3
* Swift Tools version (if applicable): 5.4

## Reproduction Steps

- create a folder and then swift package init --type executable to scaffold a swift project
- set swift-tools-version:5.4
- add  .package(name: "AWSSwiftSDK", url: "https://github.com/awslabs/aws-sdk-swift", from: "0.0.15") to the package dependencies of Package.swift
- add .product(name: "AWSIoT", package: "AWSSwiftSDK") to the executableTarget dependencies
- add import AWSIoT to the main.swift file
- compile on Linux in a Docker

Dockerfile
FROM swift:5.4.3-amazonlinux2 as builder

RUN yum -y install git jq tar zip openssl-devel
WORKDIR /build-lambda
RUN mkdir -p /Sources/swift-lambda-function/
RUN mkdir -p /Tests/swift-lambda-function/
ADD /Sources/ ./Sources/
ADD /Tests/ ./Tests/
COPY Package.swift .
RUN cd /build-lambda && swift package clean && swift build -c release

## Observed Behavior
The compile throws an error.  I do not see a specific error message.  There are many warnings, though, regarding 'additionalMetricsToRetain' is deprecated: Use additionalMetricsToRetainV2.

It does not look like that is the error, but I do not see any specific error.

I have seen this in the past with prior reported compilation issues on Linux that were a segfault with not much info displayed.

If I change the dependency to something else like AWSDynamoDB, it compiles without error.

## Expected Behavior
app should compile

**Comment by dave-moser** [comment]
attached is the output from the swift build in the Docker container if it is helpful.  I do not see any specific error
[aws-sdk-iot-errors.txt](https://github.com/awslabs/aws-sdk-swift/files/7531267/aws-sdk-iot-errors.txt)
.

**Comment by wooj2** [comment]
Thanks for the detailed bug report.  I did not try building on docker, but I tried compiling on an **AL2 instance** with swift tools 5.4.3 and I was able to get my project to compile.

Despite having the same version of Swift, I did have a couple differences in my dev environment:
* I'm using "0.0.16" ( although, the changes between 0.0.15 and 0.0.16 should be irrelevant for the IoT use case)
* Added the following to my Package.swift file -- but again, this should be irrelevant
```
    platforms: [
        .macOS(.v10_15), .iOS(.v13)
    ],
```
For your use case, is it critical that you build in a docker container, or would it be possible if you just work on an AL2 instance?

With regards to "why this doesn't work in a container" -- I suspect there is some difference in compiling within a container which makes the swift compiler "unhappy".  For example, Dynamo's DynmaoDBClient.swift is 217kb, where IoT's client.swift is 770kb.  Similarly, Dynamo's "Models.swift" file is 1.34MB while IoT's is at 3.52MB -- One theory is that swift isn't giving you an error because these files are just too large and swift is just segfaulting.

Let me know if running a container is critical to your application -- if so, i can try some to break up these files and see where things are failing.

**Comment by dave-moser** [comment]
Thanks fo looking into it.  Using Docker for the builds is crucial.  Most of the work we do is with Server Side Swift and developing on a Mac. For example, deploying Lambda functions to AWS. Using Docker is really the only practical way to compile the Swift code on your Mac.

**Comment by dave-moser** [comment]
Thanks for the info John.  I bumped the RAM allocated to Docker on my machine from the default of 2GB up to 4GB and the compile worked.  Good to know.  Thanks!
