### ISSUE TITLE
Connections and Connection Pooling

### ISSUE THREAD

**Issue by ganeshnj** [awslabs/aws-sdk-swift#702]
### Describe the feature

Because we use CRT for HTTP client, we are mostly complaint with ref arch. However there are configuration which are not exposed in the CRT HTTP client to the customers such as TLS version, HTTP version. Such configuration must be available to customer to play with.

### Use Case

Consistence interface.

### Proposed Solution

- [ ] Create design based on 951DAh0EOP4s
- [ ] Implementation

### Acknowledgements

- [ ] I may be able to implement this feature request
- [X] This feature might incur a breaking change

**Comment by ceopaludetto** [comment]
It will be possible to disable TLS? Today the integration with localstack is kinda tough since we need to write our own http engine(as pointed by @jcjimenez in https://github.com/awslabs/aws-sdk-swift/issues/593#issuecomment-1416489965). I think the default engine should disable TLS when the endpoint protocol is HTTP or somehow provide a option to disable it. What do you think?

**Comment by jbelkins** [comment]
> It will be possible to disable TLS?

It will definitely be in the future, but not at this time.  Unfortunately I don't have a timeframe for supporting this feature.
