### ISSUE TITLE
Improve URL Query Item creation

### ISSUE THREAD

**Issue by epau** [awslabs/aws-sdk-swift#714]
### Describe the feature

When implementing https://github.com/awslabs/smithy-swift/pull/468 it became clear that there is much room for improvement in our handling of query item creation. 
Currently much logic resides in the codegen flow and ideally we'd move as much logic as possible to native swift code. 

A rough idea is to define an item description that properly describes a query item and then define a factory that converts item descriptions to url query items using our business logic. 

```swift 
struct ItemDescription {
    let name: String
    let value: String? 
    let isRequired: Bool
}

struct QueryItemFactory {
    static func makeItems(_ descriptions: [ItemDescription]) throws -> [URLQueryItem] {
        descriptions.forEach { 
             // if required and value is nil then throw error
             // if value is nil then don't create a query item 
             // else -> create a query item with the name and value pair
        }
    }
}
```

### Use Case

N/A

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by sichanyoo** [comment]
As of today AWS Swift SDK has no plan to move away from current structure of [generating query item providers based on the model](https://github.com/smithy-lang/smithy-swift/blob/main/smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/middlewares/providers/HttpQueryItemProvider.kt) and [using it](https://github.com/smithy-lang/smithy-swift/blob/main/smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/middlewares/OperationInputQueryItemMiddleware.kt) with the [query item runtime middleware](https://github.com/smithy-lang/smithy-swift/blob/main/Sources/ClientRuntime/Networking/Http/Middlewares/QueryItemMiddleware.swift). Most likely due to context being lost over time and codebase changing overtime, I don't see the need nor benefit for moving query item creation to runtime. Closing ticket now.
