### ISSUE TITLE
Consider adding a common base class for all service clients

### ISSUE THREAD

**Issue by shepazon** [awslabs/aws-sdk-swift#767]
### Describe the feature

Currently, services are each represented by a client class declared as `public class FOOClient`, where `FOO` is the short form name of the service in question. It would potentially be useful for all of these to share a common base class, called something like `AWSClient`. Even if this doesn't currently offer any useful functionality, it provides for a safer way to do things like put a selection of client objects into an array or other structure.

This becomes even better if, either now or in the future, this base class offered certain common features, such as the service name or any common configuration features. Imagine someday doing something like the following (though there'd be a tad more to it in reality, hopefully this gets some of the idea across):

```swift
var myServices: [AWSClient]

myServices.append(IAMClient(...))
myServices.append(S3Client(...))
myServices.append(STSClient(...))

...

for service in myServices {
    service.setCredentials(credentialsProvider)
}
```

This snippet presumes the addition of a shared `setCredentials()` method being defined by the `AWSClient` class. Other features of the base class I could imagine eventually adding would be things like functions to get and/orset common configuration options (like the Region), control logging per-service, and the like.

What features would actually be available would be something to consider later, but just having the base class, even if it's essentially empty, would give us the option to do stuff like this going forward, and would minimally make it easy for code to identify an object as being an AWS client object.

### Use Case

Right now, I simply would like to be able to keep an array of the client objects I create so I can more easily do debugging chores with them, but the more I think about it, the more useful stuff I can think of for potential future use, but only if we add the base class *now* instead of waiting until after the first GA release to do it, which would make things potentially more complicated from a possible breakage perspective.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [X] This feature might incur a breaking change

**Comment by jbelkins** [comment]
Clients share configuration through other means since the introduction of config plugins.

Clients do all conform to the `Client` protocol, which allows for the sharing of configuration methods.  But since `Client` has an associated type, it willl likely not be useful for the case you mentioned.

Swift SDK is built to a reference architecture specification, which makes no provision for a common supertype for clients (indeed, it does not use inheritance at all.)  Further, Swift convention is to reuse / share code via protocols and protocol extensions; we do that where appropriate.

Closing this ticket; we do not plan to have a common client supertype.
